version: '3.8'

services:
  app:
    build: .
    ports:
      - "3009:3009"
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    environment:
      - NODE_ENV=development
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/usr/share/nginx/html/uploads
    depends_on:
      - app
