services:
  image-uploader:
    build: .
    container_name: image_uploader_service
    ports:
      - "3004:3009"
    volumes:
      - image_uploads_data:/usr/src/app/uploads
    environment:
      - NODE_ENV=development

  image-uploader-nginx:
    image: nginx:latest
    container_name: image_uploader_nginx
    ports:
      - "3003:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - image_uploads_data:/usr/share/nginx/html/uploads
    depends_on:
      - image-uploader

volumes:
  image_uploads_data:
